Node是单线程运行环境，一旦抛出的异常没有被捕获，就会引起整个进程的崩溃。所以，Node的异常处理对于保证系统的稳定运行非常重要。

一般来说，Node有三种方法，传播一个错误。
    使用throw语句抛出一个错误对象，即抛出异常。
    将错误对象传递给回调函数，由回调函数负责发出错误。
    通过EventEmitter接口，发出一个error事件。
3.1try catch结构
最常用的捕获异常的方式，就是使用try…catch结构。但是，这个结构无法捕获异步运行的代码抛出的异常。
3.2回调函数
Node采用的方法，是将错误对象作为第一个参数，传入回调函数。这样就避免了捕获代码与发生错误的代码不在同一个时间段的问题。
<pre>
fs.readFile('/foo.txt', function(err, data) {
  if (err !== null) throw err;
  console.log(data);
});
</pre>
3.3EventEmitter接口的error事件
发生错误的时候，也可以用EventEmitter接口抛出error事件。
<pre>
var EventEmitter = require('events').EventEmitter;
var emitter = new EventEmitter();
emitter.emit('error', new Error('something bad happened'));
</pre>
使用上面的代码必须小心，因为如果没有对error事件部署监听函数，会导致整个应用程序崩溃。所以，一般总是必须同时部署下面的代码。
<pre>
emitter.on('error', function(err) {
  console.error('出错：' + err.message);
});
</pre>